version: '3.7'
services:
  app:
    container_name: app.icex
    user: www-data
    working_dir: /app
    build:
      context: ./
      dockerfile: ./.docker/build/php-fpm.dockerfile
    depends_on:
      - db
      - redis
    restart: always
    volumes:
      - .:/app
      - ./.docker/configs/php-fpm/www.conf:/etc/php/7.1/fpm/pool.d/www.conf
    networks:
      - icex-media

  cli:
    container_name: cli.icex
    user: application
    working_dir: /app
    build:
      context: ./
      dockerfile: ./.docker/build/php-cli.dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - icex-media

  composer:
    container_name: composer.icex
    working_dir: /app
    image: "composer:latest"
    depends_on:
      - db
    volumes:
      - .:/app
      - $HOME/.composer:/home/application/.composer
    command: ["composer", "install"]

  node:
    container_name: nodejs.icex
    image: "node:latest"
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "npm install && npm run prod"

  nginx:
    container_name: nginx.icex
    image: "nginx:alpine"
    ports:
      - "80:80"
    volumes:
      - ./.docker/configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    restart: always
    depends_on:
      - app
    networks:
      - icex-media

  redis:
    container_name: redis.icex
    image: "redis:alpine"
    networks:
      - icex-media

  db:
    container_name: mysql.icex
    image: "mysql:5.7.30"
    environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=yes
          - MYSQL_DATABASE=icex
          - MYSQL_USER=root
          - MYSQL_PASSWORD=
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    networks:
      - icex-media

networks:
  icex-media:
